Removed Core Data completely
BlueOwlDev/iSpyChallenge pull request #10
Opened 2021-12-30 21:35 UTC by AlexScharch-BO

Here are the major changes in this PR:
- Removed Core Data completely
- There is a new version of `DataController` that stores and vends out data models to the view controllers
- Deleted `PhotoController`, as it wasn't really providing much value
- Updated the mock JSONs and created `APIService` and associated API models to represent the data stored in said JSONs. `APIService` is really a mock service that just returns the data from the JSONs.
- Turned the former Core Data models into plain Swift structs. These are instantiated with data from the API models and subsequently stored in `DataController`.

2021-12-30 21:38 UTC, AlexScharch-BO commented on iSpyChallenge/Data/DataController.swift
> +}
These functions are for the "New Challenge" page, should a candidate choose to build that page out. I'm wondering if we should keep this here or leave it up to candidates to implement this functionality.

If we do leave this in, I suspect we should add comparable functionality for the "Near Me" page (i.e. filtering challenges by being within some passed in distance to a lat/long).

2021-12-31 01:17 UTC, GabePires reviewed
I think I saw some `import CoreData` lines somewhere btw

2022-01-03 19:44 UTC, AlexScharch-BO commented on iSpyChallenge/Data/DataController.swift
> +            self.currentUser = self.allUsers.first
I'm open to that. The only thing is that the user should probably be one from the list, but we can mock things out that way.

2022-01-03 19:47 UTC, AlexScharch-BO commented on iSpyChallenge/Data/DataController.swift
> +            self.allUsers = apiUsers.map { User(apiUser: $0, apiChallenges: apiChallenges) }
Within the `User(apiUser:apiChallenges:)` initializer there's some filtering logic to only take the challenges that were created by `apiUser`. However, that filtering could happen in here instead of in in the initializer. Do you think that might be a little clearer?

2022-01-03 19:51 UTC, AlexScharch-BO commented on iSpyChallenge/API/APIService.swift
> +class APIService {
Part of me thinks that it might not even be worth having an `APIService` and a set of API models. Since everything is mocked out, we could do that mocking on the app model level (with `User`, `Challenge`, etc.).

Having this `APIService` is more akin to a real app, but I'm worried it might only serve to distract candidates, since I'm not sure it provides any real value to a coding challenge that uses entirely mock data.

2022-01-03 19:53 UTC, AlexScharch-BO commented on iSpyChallenge/Data/Models/User.swift
> +}
I decided to nest `challenges` under each user, so having a collection of users sort of becomes the "root" data node within `DataController`. The data model relationships certainly don't have to be arranged this way though, so I'm open alternatives.

2022-01-03 21:31 UTC, BennettSmith commented on iSpyChallenge/API/APIService.swift
> +class APIService {
I like having this APIService. It would let you mock API failures (network timeout, unexpected json response from server).  Not sure we should do that, but by having the APIService we could.

2022-01-03 21:36 UTC, BennettSmith commented on iSpyChallenge/Controllers/PhotoController.swift
> -//
I question the idea of removing this vs. providing an example of using it. There are photos for each of the sample challenges and if someone adds the ability to attach a photo to a new challenge hint this code would be useful for storing the added photo.

2022-01-03 21:37 UTC, BennettSmith commented on iSpyChallenge/Data Browser/ChallengeTableViewController.swift
> +            ChallengeRow(type: .photoHref, title: challenge?.photoImageName, detail: "photoHref")
How would the photo image name be used to find an actual photo?

2022-01-03 21:43 UTC, BennettSmith commented on iSpyChallenge/Data/DataController.swift
> +    private(set) var currentUser: User? { didSet { delegate?.dataControllerDidUpdate(self) } }
How are these delegate methods envisioned to be used? I might like to know why the data controller was updated, not just that it was updated. Also, it seems like both of these properties will likely be set in rapid succession on startup so having this notification fire twice might not be that useful.  It might be nice to have separate delegate methods for "current user changed" and "list of users changed".

2022-01-03 21:49 UTC, BennettSmith commented on iSpyChallenge/Data/DataController.swift
> +            self.currentUser = self.allUsers.first
You could assign the current user in a "login" method of the APIService. Then, you could add a call to that method in the AppDelegate. That way the behavior of the app would be more predictable; always knowing who is logged in vs. some random user.

2022-01-03 21:52 UTC, BennettSmith commented on iSpyChallenge/Data/Models/User.swift
> +}
Flipping that makes more sense to me. The challenge would be the root and it would reference the user who created it.  If we had hundreds of users playing the game, it might not make sense for the game to keep a list of all of the users. On the other hand, the game likely wants to fetch a list of challenges that are "near here" when it is launched.

2022-01-03 21:53 UTC, BennettSmith commented on iSpyChallenge/Data/Models/Rating.swift
> +    var creatorID: String
Why wouldn't this just be the User?

2022-01-03 21:54 UTC, BennettSmith commented on iSpyChallenge/Data/Models/Match.swift
> +    var creatorID: String
Why wouldn't this just be the User?

2022-01-03 21:54 UTC, BennettSmith commented on iSpyChallenge/Data/Models/Challenge.swift
> +    var creatorID: String
Why wouldn't this just be the User?

2022-01-03 21:56 UTC, BennettSmith commented on iSpyChallenge/Extensions/DataController+iSpy.swift
> +    func user(identifiedBy userID: String) -> User? {
This method seems like it might belong in the APIService more than the DataController.

2022-01-03 22:22 UTC, AlexScharch-BO commented on iSpyChallenge/Data/Models/User.swift
> +}
That sounds reasonable for a challenge to be the root object. I'll make the change.

2022-01-03 22:32 UTC, BennettSmith commented on iSpySampleData/users.json
> -{
The structure of this file came directly from the `https://randomuser.me` API. It would be nice to keep that structure unless there is a compelling reason to change it.

Here is an example of generating a list of 10 random users.

`curl 'https://randomuser.me/api/?results=10&inc=name,gender,location,email,login,picture' | jq`

2022-01-03 22:37 UTC, BennettSmith reviewed
Changes look good to me for the most part. I wonder about having user id values as part of the model objects. Perhaps the user id could be an implementation detail of the API Service? If the models had User properties instead that might feel more natural.  

Also, I would love to see us keep the format of the users.json file as-is, but updated so the login information includes the uuid for each user. That would give you a unique value to use in the challenges.json file when referencing users.

2022-01-03 22:52 UTC, AlexScharch-BO commented on iSpyChallenge/Data/DataController.swift
> +    private(set) var currentUser: User? { didSet { delegate?.dataControllerDidUpdate(self) } }
Could you provide an example of when it might be useful to know why the data was updated, and which class would be interested in that reason?

I envisioned this delegate method as letting whatever owns `DataController` (the tab bar controller in this project) know that it must update any of the things it owns with the updated data from `DataController`. The idea was that something like the data browser could have its view updated when the challenges are modified from another tab in the app, though ironically I didn't actually implement the data browsing UI responding to data changes.

Normally I would have used Combine and made these properties `@Published`, but I'm not sure incorporating Combine into an interview project is a good idea, as there are probably many developers still who aren't very familiar with it yet, especially midlevel engineers.

Thinking about things a bit more now, merely sending a delegate callback to a single object doesn't really work well with the fact that we pass `DataController` around everywhere, because there are many parties who directly rely on `DataController` and thus would be interested in the callback. I don't love this idea, but perhaps this callback should be replaced with a notification instead, so that all VCs can respond to changes in `DataController`.

With respect to this callback/notification firing 2+ times in rapid succession, you're correct. I don't love the idea of having a separate broadcast for each piece of data that `DataController` owns, though, because it creates extra overhead when adding new data to `DataController`. Perhaps a nested `Data` or `AppData` struct could wrap these two properties (and other properties, down the line). Something like:

```swift
class DataController {
    struct Data {
        var currentUser: User?
        var allUsers: [User]
    }
    
    private(set) var data: Data { didSet { delegate?.dataControllerDidUpdate(self) } }
    
    ...
}
```

Anything operation in `DataController` that writes to `data` would then want to make all writes in a single assignment statement, rather than modifying property by property.

2022-01-03 22:58 UTC, AlexScharch-BO commented on iSpyChallenge/Data/Models/Rating.swift
> +    var creatorID: String
Because a user / users are the root level data structure, referencing an actual user here would lead to reference cycles*.

If we make a challenge / collection of challenges the root level data structure (and remove the `challenges` property from `User`), then we could put actual user structs here. The issue with that is that we would have duplicated users throughout memory. That's not so much an issue for memory usage, since Swift is smart about only copying value types on write, but it's an issue when updating data. If something changes on a user for whatever reason, you have to find _all_ instances of that user in the data tree and update those as well.

*Because these data models are value types, these wouldn't be actual reference cycles, more like logical reference cycles

2022-01-03 23:00 UTC, AlexScharch-BO commented on iSpyChallenge/Data/Models/Rating.swift
> +    var creatorID: String
As a somewhat relevant side-note, working on this Core Data removal was the first time I really thought about the differences between relational data structures and data structured in a tree. It was interesting to explore.

2022-01-03 23:01 UTC, AlexScharch-BO commented on iSpyChallenge/Extensions/DataController+iSpy.swift
> +    func user(identifiedBy userID: String) -> User? {
I'm guessing you're imagining that this function represents the idea of asynchronously fetching a user from the network? The idea of this func was to provide an access point to get a user (that's already been loaded into memory) from one of the `createrID`s on the other data structs.

2022-01-03 23:04 UTC, AlexScharch-BO commented on iSpySampleData/users.json
> -{
The thinking of changing this was just that it included a lot of data we don't need. The stuff around authentication (like the `password` field) also felt very odd to expose in a list of users that the app would have access to.

2022-01-03 23:11 UTC, AlexScharch-BO commented on iSpyChallenge/Data Browser/ChallengeTableViewController.swift
> +            ChallengeRow(type: .photoHref, title: challenge?.photoImageName, detail: "photoHref")
I took the list of embedded photos in the project / build to be more or less a convenience for hosting the challenge and match photos, rather than spinning up an actual API to reference them. Thus the mock JSON returns the photo names that are embedded in the project, and the view controllers must know to load the images that way.

I definitely don't think this is ideal. (The view controllers being affected by the decision of where to host these images is a code smell IMO.) Is there a better way we can represent this in the mock JSON files? I'm not sure if it's possible to return URLs that will point to where the images will be embedded in the filesystem, but if so I think that would be ideal.

2022-01-04 18:40 UTC, AlexScharch-BO commented on iSpyChallenge/Data/Models/User.swift
> +}
I realized last night that flipping things so that each challenge contains a `User` is not so simple. Because not all users will have created a challenge, to have access to a full list of users we either have to
- store one in memory (as the code is doing now)
- compute one by iterating over all other data (challenges, matches and ratings)

The second of those two creates the issue of likely having duplicate instances of one or more users. While that's not impossible to manage, it creates the possibility that data will get out of sync.

Thus I think we need to maintain, at the top level, a list of all users the app is aware of. Whether or not each user contains a `challenges` array, however, is another decision, as I don't think there's any issue with keeping a separate array of all challenges or embedding each user's challenges directly under the user.

2022-01-12 21:10 UTC, BennettSmith commented on iSpyChallenge/Data/Models/User.swift
> +}
Sorry for the late reply here. Could you remind me why we need a list of all users in the first place.

2022-01-12 23:07 UTC, BennettSmith commented on iSpyChallenge/Data/Models/Rating.swift
> +    var creatorID: String
I would try to maintain the list of users and the list of challenges separately. Then, the relationships between specific users and challenges could be handled using weak references (and possibly some clever use of `@propertyWrapper`).

This Medium article illustrates something similar to what I had in mind. 
https://medium.com/@apstygo/implementing-weak-arrays-with-property-wrappers-in-swift-680e2b3c9fca

2022-01-12 23:10 UTC, BennettSmith commented on iSpyChallenge/Extensions/DataController+iSpy.swift
> +    func user(identifiedBy userID: String) -> User? {
I understood that it was for lookup locally. My thought was that if the data model managed by the DataController no longer had things like `creatorID`, but had weak references to the actual objects then this method would only be needed inside the `APIService` where the mapping between ID and object was handled.

2022-01-12 23:12 UTC, BennettSmith commented on iSpySampleData/users.json
> -{
Leaving the structure as-is, but only decoding the portions we need would preserve the ability to easily update this file if/when we wanted to. I don't see what is gained by changing it.

2022-01-12 23:13 UTC, BennettSmith commented on iSpySampleData/users.json
> -{
I agree that we shouldn't have things like the password, various hash values, etc. in the User class.

2022-01-12 23:18 UTC, BennettSmith commented on iSpyChallenge/Data/DataController.swift
> +    private(set) var currentUser: User? { didSet { delegate?.dataControllerDidUpdate(self) } }
I do prefer the idea of some sort of observer pattern here instead of the delegate.  

More granular notifications would provide the observers with a hint about how the data changes. If a new challenge is added it might be useful for the observers to know that instead of just being told that the data has changed.

2022-01-12 23:19 UTC, AlexScharch-BO commented on iSpyChallenge/Data/Models/Rating.swift
> +    var creatorID: String
I thought of using reference types for the data models instead of structs. There are some downsides:
- Loss of automatic `Hashable`, `Equatable` and `Codable` conformance (though I think `Equatable` is probably the only useful one of the three in our context)
- `DataController` loses having full control over its data. If we use reference types, `DataController` vends out pointers to its data instances, enabling modification of the data without `DataController'`s knowledge. If we use value types, then `DataController` vends out copies, keeping its own data safe.

2022-01-13 21:16 UTC, AlexScharch-BO commented on iSpySampleData/users.json
> -{
I just went in to revert the changes to this JSON and realized that, while I did mostly remove fields, I also added `id`. Would that get in the way of using `randomuser.me` in the future?

2022-04-27 01:28 UTC, BennettSmith commented
@AlexScharch-BO I pushed one small change to the branch and have a question.  The change was to address an error in the simulator when the data browser loaded the user avatar images.  Now the question. How do you envision the candidate interacting with the DataController to add a new challenge or match?

2022-04-27 03:21 UTC, AlexScharch-BO commented
Gotcha. Looks good, I like the placeholder image :)

I imagine that the candidate may add methods to `DataController` to provide them with the operations they wish to execute. For example, adding a new challenge might look something like

```swift
func addChallengeForCurrentUser(hint: String,
                                latitude: Double,
                                longitude: Double,
                                photoImageName: String) {
    guard let currentUser = currentUser, let currentUserIndex = currentUserIndex else {
        return
    }
    
    let challenge = Challenge(id: UUID().uuidString,
                              hint: hint,
                              latitude: latitude,
                              longitude: longitude,
                              photoImageName: photoImageName,
                              creatorID: currentUser.id)
    
    allUsers[currentUserIndex].challenges.append(challenge)
    self.currentUser = allUsers[currentUserIndex]
}
```

where they might add this as a helper function:

```swift
private var currentUserIndex: Int? {
    allUsers.firstIndex(where: { $0 == currentUser })
}
```

2022-04-27 03:22 UTC, AlexScharch-BO commented
An additional thought: maybe `currentUserIndex` should be a mutable var, and `currentUser` should be computed. Might be helpful if we made that change and gave them access to both.

2022-04-27 03:24 UTC, AlexScharch-BO commented
That implementation would be the bare bones implementation. Extra points to the interviewer if they route a call to `APIService` and let that create/return a challenge

2022-04-27 16:42 UTC, BennettSmith commented
I guess it depends on what we are trying to learn from the technical interview.  In the past we provided all of the crud operations and expected candidates to focus on the UI and hoped to see how they took advantage of existing code in the data layer.  I'm not opposed to the new approach, but it does mean we are asking the candidate something different.  

I'm mostly interested in seeing if the candidate can build the UI given a someone vague set of requirements. They are given a lot of latitude to go broad or deep in their approach. 

We are asking them to build the UI to create a new challenge. Collecting the information about the challenge hint, capturing a photo, getting the location, etc. These all show an understanding of the various iOS frameworks. Maybe our interest lies more in trying to learn their architectural style.  Seeing how well they understand the architecture and the choices they make to extend it would be nice too.  

The 3 hour window we provide may not be enough time to cover both UIKit / iOS knowledge and the deeper architectural stuff.

2022-04-27 16:51 UTC, AlexScharch-BO commented
That all makes a lot of sense. I think implementing the CRUD operations for them so that they can just work on UI / interact with the other Apple frameworks makes sense. I do like the idea of getting to see how they address larger architectural concerns within the project, but 3 hours really is a limited window.

I can't remember if we reserve the end of the interview to ask the candidate additional questions, but I like the idea of asking them what things they might improve about the project. This would give them a chance to show architectural knowledge, at least at the conversational level. We could ask them things like how to manage the size and responsibility of `DataController` as more features and data types are added to the project over time.

2022-04-27 20:52 UTC, BennettSmith requested changes
Looks great to me with one remaining question about how the caller of the DataController gets feedback on the new crud operations.

2022-04-27 20:52 UTC, BennettSmith commented on iSpyChallenge/Data/DataController.swift
> +        guard let currentUser = currentUser else {
I wonder if we should add another guard that ensures the provided `challengeId` is valid.

2022-04-27 20:52 UTC, BennettSmith commented on iSpyChallenge/Data/DataController.swift
> +    func addMatch(forChallenge challengeId: String,
Should this method provide some sort of status back? Should it be async?

2022-04-27 20:52 UTC, BennettSmith commented on iSpyChallenge/Data/DataController.swift
> +    func addChallengeForCurrentUser(hint: String,
Should this method provide some sort of status back? Should it be async?

2022-04-27 20:54 UTC, AlexScharch-BO commented on iSpyChallenge/Data/DataController.swift
> +    func addMatch(forChallenge challengeId: String,
That's right, I forgot to add a callback! Thanks for the reminder. I'll add that now.

2022-04-27 20:55 UTC, AlexScharch-BO commented on iSpyChallenge/Data/DataController.swift
> +        guard let currentUser = currentUser else {
That sounds reasonable. The guard should validate that the challenge does _not_ belong to the current user, correct?

2022-04-27 21:11 UTC, BennettSmith approved these changes
I like it! This should be a lot easier for candidates to grok than the older Core Data version.

2022-04-27 21:13 UTC, merged